### ISSUE TITLE
BOM (Byte Order Mark) IG-Checker

### ISSUE THREAD

**Issue by Pinauen** [GivTG/GIV.Interlis2.Tool#1]
Problematik mit Files mit oder ohne BOM in Abhängigkeit mit den Voreinstellungen des IG-Checkers:

Die mit dem GIV-Tool transformierten Daten generieren beim MoCheck auf dem ThurGIS-Upload folgende Fehlermeldung und die Daten werden dadurch nicht an den VSA-Check weitergeleitet: 
  
    --> „input file should not start with a byte order mark (BOM)“ 
  
Die Meldung erscheint auch manuell mit dem IG-Checker. 
  
![grafik](https://user-images.githubusercontent.com/105843645/169244375-5f415fc8-bd68-4388-a047-b89035d69818.png)

Spontaner Vorschlag wäre folgender: 
-	Standardmässig schreibt der GIV-Konverter UTF-8 mit BOM. 
-	Es gibt einen Parameter, der bei der Konvertierung mitgegeben wird um auch UTF-8 ohne BOM zu konvertieren.

**Comment by urss1** [comment]
Gemäss Abklärungen (swisstopo und Infogrips) darf kein BOM geschrieben werden, dies wurde bereits in der Version 1.1 angepasst.
