### ISSUE TITLE
Parameteraufruf ist case-sensitive

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [GivTG/GIV.Interlis2.Tool#20]
Der Aufruf
`"GIV Interlis2 Tools Console.exe" --type splitDSS2melio ....`
ergibt
`Der angegebene Typ [splitDSS2melio] wurde nicht gefunden.`

Grund:
melio schreibt man gross mit Melio ..

M.E. sollte das nicht case-sensitiv sein, wenn nicht ein zwingender Grund dafür spricht.

**Comment by urss1** [comment]
Die Typenbezeichnungen wurden vereinheitlicht und bleiben case-sensitive. Dies wurde so in den Anleitungen entsprechend Dokumentiert.
