### ISSUE TITLE
Dokumentation auf https://wiki.giv.tg.ch/index.php/GIV_Interlis2_Tool ist falsch

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [GivTG/GIV.Interlis2.Tool#21]
Dort wird der Befehlszeilenaufruf mit 
`"GIV Interlis2 Tools.exe" --type  ...`
beschrieben. Das ruft aber immer die GUI auf; anscheinend muss man die andere EXE aufrufen:
`"GIV Interlis2 Tools Console.exe" --type ...`

**Comment by urss1** [comment]
Die Beschreibungen wurden komplett überarbeitet und die Beispielaufrufe sollten nun korrket sein.

**Comment by Pierre-de-la-Verre** [comment]
Die Dokumentation schreibt 
"GIV Interlis2 Tools Console.exe" -h (mit s), aber die Programme heissen 
"GIV Interlis2 Tool Console.exe" (ohne s)
