### ISSUE TITLE
Kosmetik: "MainWindow" in der Taskleiste

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [GivTG/GIV.Interlis2.Tool#22]
Wenn die GUI offen ist, wird bei mir (Win10) der Eintrag in der Taskleiste mit "MainWindow" beschriftet. Nicht dramatisch, aber auch nicht schön ..

**Comment by urss1** [comment]
Anzeige geändert auf "GIV - Interlis2 Tool"
