### ISSUE TITLE
GUI-Kosmetik: Beschriftung der Buttons

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [GivTG/GIV.Interlis2.Tool#27]
Bei der Auswahl der Quell-Datei sollte so wie bei den beiden anderen Buttons "Wählen ..." (mit Punkten) verwendet werden anstelle des aktuellen "Öffnen"

**Comment by urss1** [comment]
Neue Schaltfläche:
![grafik](https://github.com/user-attachments/assets/cb2d09b4-3b74-481f-8d7a-2c21364c2fc1)
