### ISSUE TITLE
Testdatei bereitstellen?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [GivTG/GIV.Interlis2.Tool#4]
Wäre es möglich, eine Testdatei (oder mehrerer ..) bereitzustellen?

**Comment by urss1** [comment]
Aktuell ist es nicht vorgesehen, dass es einen eigenen Test-Datensatz für das Tool bereitgestellt wird.
Zum Ausprobieren kann eine beliebige Interlis-Datendatei (XTF, XML) im DSS_2020_LV95 Modell verwendet werden.

Für was sollte die Testdatei beinhalten, was ein ordentlicher Datensatz aus einem GIS Systemes nicht beinhaltet?

**Comment by Pierre-de-la-Verre** [comment]
Wäre für den Fall praktisch, wenn man momentan keine Datei zur Hand hat. Kommt aber sicher selten vor und ist nicht so wichtig.
