### ISSUE TITLE
Anmerkungen zur GUI

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [GivTG/GIV.Interlis2.Tool#5]
Ein paar Anmerkungen / Vorschläge / Diskussionsbeiträge zur GUI bzw. Grundfunktionen

Allgemeines:
- Über / About einbauen: Wie in anderen Programmen - was ist das, Auftraggeber, Programmierer, Downloadlink, Updatefunktion, Lizenz, Hilfefunktion
- Hilfe für GUI und vor allem für Befehlszeilenversion bereitstellen

Dateifunktionen:
- Zieldatei - Namensvorschläge: Gut; aber MEL und Mel-gefiltert sollten unterschiedliche Namen vorschlagen
- Protokolldatei - Namen: Sollte eventuell einen weiteren String wie "..._GIV" oder so haben; bei mir schlägt sich der Namensvorschlag mit dem Log des Ilivalidator. Die Frage "Ein Log für alle Aufträge zu dieser Quelle" oder "jeder Auftrag kriegt ein eigenes 
- Überschreibewarnung: Bestehende Zieldateien werden ohne Warnung überschrieben. Normal kommt eine Abfrage oder eine dauerhafte Option: Überschreiben / Neuer Name / Aufnummerieren / ....
- Fehlerwarnungen - Quelle: Erwischt man eine falsche XTF (z.B. Fernwärme), kommt trotzdem die Meldung "Erfolgreich konvertiert". Über den Modellnamen müsste man das abfangen können.
- Fehlerwarnung - Ergebnis: Wenn man eine korrekte DSS Datei filtert und gar keine Objekte (Leitungen, Objekte, .) übrigbleiben, dann könnte eine Warnung erscheinen.
- Filterfunktion: es ist nicht klar, was hier geschieht. 
- - Input DSS -> Output DSS_MEL und gefiltert?
- - Input DSS -> Output DSS und gefiltert?
- - Input DSS_MEL -> Output DSS_MEL und gefiltert?
- Das Fenster Info-Logger und die Log-Datei zeigen unterschiedliche Informationen bzw. Formulierungen. Input- und Output stehen nur im Log, Zeiten nur im Fenster.
- Im Log könnten etwas mehr Metainformationen stehen (siehe z.B. Ilivalidator): Anwender, Datum, Uhrzeit, Programmversion, optisch bessere Trennung (Leerzeilen, Trennstriche) zwischen den Logs der verschiedenen Aufträge
- ist die Protokolldatei schreibgeschützt, erscheint korrekt die Fehlermeldung " - Ausführung ist ein Problem aufgetretten: ...". Das wird aber leicht übersehen und könnte durch ein Dialogfenster, Warnton, Farbwechsel etc. etwas stärker betont werden.
- Ist die Zieldatei schreibgeschützt, kommt keine Fehlermeldung, sondern nur die falsche Meldung "Konvertierung erfolgreich abgeschlossen"

Schöne Weihnachtszeit!

Nachtrag: Interessant wäre auch die Option, in den COMMENT Tag der Ausgabedatei Informationen zu schreiben (Quelldatei etc.)

**Comment by urss1** [comment]
Habe den Fall als "duplicate" definiert. Die Anregungen wurden in einzelen Issues übernommen um diese laufend anzugehen und die Wünsche abzuarbeiten.
Somit wir dieser Fall auch geschlossen, bitte direkt bei den einzelenen Fällen den Status und die Kommentare beachten.
