### ISSUE TITLE
Protokolldatei - Namensvorschlag verbessern

### ISSUE THREAD

**Issue by urss1** [GivTG/GIV.Interlis2.Tool#9]
Original-Meldung im Fall "#5 Anmerkungen zur GUI" - Benutzer: Pierre-de-la-Verre - Meldung vom 22.12.2022
"Protokolldatei - Namen: Sollte eventuell einen weiteren String wie "..._GIV" oder so haben; bei mir schlägt sich der Namensvorschlag mit dem Log des Ilivalidator. Die Frage "Ein Log für alle Aufträge zu dieser Quelle" oder "jeder Auftrag kriegt ein eigenes"

**Comment by urss1** [comment]
Verbesserter Vorschlag für den Dateiname der Protokoll-Datei.

**Comment by Pierre-de-la-Verre** [comment]
Die Namensvorschläge der Ziel- und der Protokolldatei sind für MEL und SPLIT_MEL gleich. Da könnten eigene Namen wahrscheinlich besser sein.
